stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  tags:
    - myserver
  script:
    - docker build -t "$PROJECT_NAME:ci_job_$CI_PIPELINE_ID" .

deploy:
  stage: deploy
  only:
    - master
  tags:
    - myserver
  script:
    - docker stop $PROJECT_NAME && docker rm $PROJECT_NAME || true
    - docker run --restart=unless-stopped --name=$PROJECT_NAME -d -p 8111:8000 "$PROJECT_NAME:ci_job_$CI_PIPELINE_ID"
